# Generated by Django 5.2.4 on 2025-11-19 07:51

from django.db import migrations

def populate_pest_alerts(apps, schema_editor):
    PestAlert = apps.get_model('pest_alerts', 'PestAlert')
    
    alerts = [
        # Rice
        {'crop': 'rice', 'pest_name': 'Brown Planthopper', 'min_temp': 25, 'max_temp': 35, 'min_humidity': 70, 'symptoms': 'Yellowing and drying of leaves, stunted growth', 'prevention': 'Use resistant varieties, maintain proper spacing', 'treatment': 'Apply imidacloprid or thiamethoxam', 'severity': 'high'},
        {'crop': 'rice', 'disease_name': 'Blast Disease', 'min_temp': 20, 'max_temp': 30, 'min_humidity': 80, 'symptoms': 'Diamond-shaped lesions on leaves', 'prevention': 'Use disease-free seeds, avoid excessive nitrogen', 'treatment': 'Apply tricyclazole fungicide', 'severity': 'critical'},
        # Wheat
        {'crop': 'wheat', 'pest_name': 'Aphids', 'min_temp': 15, 'max_temp': 25, 'min_humidity': 60, 'symptoms': 'Curled leaves, sticky honeydew', 'prevention': 'Early sowing, remove weeds', 'treatment': 'Spray dimethoate or imidacloprid', 'severity': 'medium'},
        {'crop': 'wheat', 'disease_name': 'Rust', 'min_temp': 15, 'max_temp': 25, 'min_humidity': 70, 'symptoms': 'Orange-red pustules on leaves', 'prevention': 'Use resistant varieties', 'treatment': 'Apply propiconazole fungicide', 'severity': 'high'},
        # Maize/Corn
        {'crop': 'maize', 'pest_name': 'Fall Armyworm', 'min_temp': 20, 'max_temp': 35, 'symptoms': 'Holes in leaves, damaged cobs', 'prevention': 'Early planting, crop rotation', 'treatment': 'Apply chlorantraniliprole', 'severity': 'critical'},
        {'crop': 'corn', 'pest_name': 'Fall Armyworm', 'min_temp': 20, 'max_temp': 35, 'symptoms': 'Holes in leaves, damaged cobs', 'prevention': 'Early planting, crop rotation', 'treatment': 'Apply chlorantraniliprole', 'severity': 'critical'},
        # Cotton
        {'crop': 'cotton', 'pest_name': 'Bollworm', 'min_temp': 25, 'max_temp': 35, 'symptoms': 'Damaged bolls, holes in leaves', 'prevention': 'Use Bt cotton, pheromone traps', 'treatment': 'Apply spinosad or emamectin benzoate', 'severity': 'high'},
        {'crop': 'cotton', 'pest_name': 'Whitefly', 'min_temp': 27, 'max_temp': 35, 'min_humidity': 60, 'symptoms': 'Yellowing leaves, sooty mold', 'prevention': 'Yellow sticky traps, remove weeds', 'treatment': 'Apply thiamethoxam or acetamiprid', 'severity': 'high'},
        # Tomato
        {'crop': 'tomato', 'disease_name': 'Late Blight', 'min_temp': 15, 'max_temp': 25, 'min_humidity': 80, 'symptoms': 'Brown spots on leaves and fruits', 'prevention': 'Proper spacing, avoid overhead watering', 'treatment': 'Apply mancozeb or copper fungicide', 'severity': 'critical'},
        {'crop': 'tomato', 'pest_name': 'Fruit Borer', 'min_temp': 20, 'max_temp': 30, 'symptoms': 'Holes in fruits, damaged leaves', 'prevention': 'Use pheromone traps, remove infected fruits', 'treatment': 'Apply spinosad or Bacillus thuringiensis', 'severity': 'high'},
        # Potato
        {'crop': 'potato', 'disease_name': 'Late Blight', 'min_temp': 10, 'max_temp': 25, 'min_humidity': 75, 'symptoms': 'Dark lesions on leaves and tubers', 'prevention': 'Use certified seeds, proper drainage', 'treatment': 'Apply metalaxyl or mancozeb', 'severity': 'critical'},
        # Sugarcane
        {'crop': 'sugarcane', 'pest_name': 'Early Shoot Borer', 'min_temp': 25, 'max_temp': 35, 'symptoms': 'Dead hearts, wilting shoots', 'prevention': 'Use healthy setts, remove trash', 'treatment': 'Apply chlorpyrifos or fipronil', 'severity': 'high'},
    ]
    
    for alert_data in alerts:
        PestAlert.objects.create(**alert_data)

class Migration(migrations.Migration):

    dependencies = [
        ('pest_alerts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_pest_alerts),
    ]
